---
# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: secret - presence - secretsFromFolder
templates:
  - common.yaml
values:
  - ../_values/controllers_main_default_container.yaml
set:
  secretsFromFolder:
    enabled: true
    basePath: testFiles
    overrides:
      escaped:
        fileAttributeOverrides:
          test_2.yaml:
            escaped: true
tests:
  - it: secret from folder is present
    asserts:
      - not: true
        containsDocument:
          apiVersion: v1
          kind: Secret
          name: release-name-binary
          any: true
      - containsDocument:
          apiVersion: v1
          kind: Secret
          name: release-name-escaped
          any: true
      - containsDocument:
          apiVersion: v1
          kind: Secret
          name: release-name-envfile
          any: true

  - it: combined with secrets
    set:
      secrets:
        extra:
          stringData:
            foo: bar
    asserts:
      - not: true
        containsDocument:
          apiVersion: v1
          kind: Secret
          name: release-name-binary
          any: true
      - containsDocument:
          apiVersion: v1
          kind: Secret
          name: release-name-escaped
          any: true
      - containsDocument:
          apiVersion: v1
          kind: Secret
          name: release-name-envfile
          any: true
      - containsDocument:
          apiVersion: v1
          kind: Secret
          name: release-name-extra
          any: true
